#version: "3"

#services:
gwy:
  build: ./gwy
  ports:
    - "80:8080"
  links:
    - ms1
    - auth

auth:
  build: ./auth2
  expose:
    - "8080"
# ms1:
#   build: ./ms1
#   expose:
#     - "8080"

ms1:
  build: ./ms2
  # image: rocker/shiny
  ports:
    - "9999:3838"
  expose:
    - "3838"
